# Change these first
owner: emign # Your GitHub organization or username, where this repository lives
repo: uptime_netman # The name of this repository

sites:
  - name: asg netman
    url: https://gymamsee.zapto.org/login/login.html

status-website:    
  baseUrl: /uptime_netman
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: netman
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime ASG Netman
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
